// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Dysar/url-crawler/backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// JobRepository is an autogenerated mock type for the JobRepository type
type JobRepository struct {
	mock.Mock
}

// Enqueue provides a mock function with given fields: ctx, urlID
func (_m *JobRepository) Enqueue(ctx context.Context, urlID int64) (*models.CrawlJob, error) {
	ret := _m.Called(ctx, urlID)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 *models.CrawlJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.CrawlJob, error)); ok {
		return rf(ctx, urlID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.CrawlJob); ok {
		r0 = rf(ctx, urlID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CrawlJob)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, urlID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *JobRepository) GetByID(ctx context.Context, id int64) (*models.CrawlJob, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.CrawlJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.CrawlJob, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.CrawlJob); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CrawlJob)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByURLID provides a mock function with given fields: ctx, urlID
func (_m *JobRepository) GetByURLID(ctx context.Context, urlID int64) (*models.CrawlJob, error) {
	ret := _m.Called(ctx, urlID)

	if len(ret) == 0 {
		panic("no return value specified for GetByURLID")
	}

	var r0 *models.CrawlJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.CrawlJob, error)); ok {
		return rf(ctx, urlID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.CrawlJob); ok {
		r0 = rf(ctx, urlID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CrawlJob)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, urlID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, errMsg
func (_m *JobRepository) UpdateStatus(ctx context.Context, id int64, status models.CrawlJobStatus, errMsg *string) error {
	ret := _m.Called(ctx, id, status, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.CrawlJobStatus, *string) error); ok {
		r0 = rf(ctx, id, status, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewJobRepository creates a new instance of JobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobRepository {
	mock := &JobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
