// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Dysar/url-crawler/backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// ResultRepository is an autogenerated mock type for the ResultRepository type
type ResultRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, res
func (_m *ResultRepository) Create(ctx context.Context, res models.CrawlResult) (*models.CrawlResult, error) {
	ret := _m.Called(ctx, res)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.CrawlResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CrawlResult) (*models.CrawlResult, error)); ok {
		return rf(ctx, res)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CrawlResult) *models.CrawlResult); ok {
		r0 = rf(ctx, res)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CrawlResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CrawlResult) error); ok {
		r1 = rf(ctx, res)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByURLID provides a mock function with given fields: ctx, urlID
func (_m *ResultRepository) GetByURLID(ctx context.Context, urlID int64) (*models.CrawlResult, error) {
	ret := _m.Called(ctx, urlID)

	if len(ret) == 0 {
		panic("no return value specified for GetByURLID")
	}

	var r0 *models.CrawlResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.CrawlResult, error)); ok {
		return rf(ctx, urlID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.CrawlResult); ok {
		r0 = rf(ctx, urlID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CrawlResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, urlID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewResultRepository creates a new instance of ResultRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResultRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResultRepository {
	mock := &ResultRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
