// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Dysar/url-crawler/backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// URLRepository is an autogenerated mock type for the URLRepository type
type URLRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, url
func (_m *URLRepository) Create(ctx context.Context, url string) (*models.URL, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.URL, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.URL); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *URLRepository) GetByID(ctx context.Context, id int64) (*models.URL, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.URL, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.URL); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, page, limit, sortBy, order
func (_m *URLRepository) List(ctx context.Context, page int, limit int, sortBy string, order string) ([]models.URL, int64, error) {
	ret := _m.Called(ctx, page, limit, sortBy, order)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.URL
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) ([]models.URL, int64, error)); ok {
		return rf(ctx, page, limit, sortBy, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) []models.URL); ok {
		r0 = rf(ctx, page, limit, sortBy, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string) int64); ok {
		r1 = rf(ctx, page, limit, sortBy, order)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string) error); ok {
		r2 = rf(ctx, page, limit, sortBy, order)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewURLRepository creates a new instance of URLRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLRepository {
	mock := &URLRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
